### ISSUE TITLE
/dist not updated

### ISSUE THREAD

**Issue by yukaitseng** [aalfiann/recacheman#2]
Hi,

Could you re-build this module and update recachegoose again?

The _objectSpread() is still in the front of this.options.

```
this.options = _objectSpread(_objectSpread({}, options), {}, {
      Promise: _Promise,
      delimiter: delimiter,
      prefix: prefix,
      ttl: ttl,
      count: 1000
    });
```

Thanks,

**Comment by aalfiann** [comment]
Ahh sorry my mistake.

Now have been built.
